let mMapData={
	map:[
		[08,08,08,08,08,08,08,07,00,00,00,00,00,00,00],
		[08,08,08,08,08,08,08,06,09,09,09,09,09,09,09],
		[08,08,08,08,08,08,08,06,09,09,09,09,09,09,09],
		[08,08,08,08,08,08,08,05,04,04,04,04,04,04,04],
		[08,08,08,08,08,08,08,08,08,08,08,08,08,08,08],
		[10,10,10,08,10,10,10,08,08,08,08,08,08,08,08],
		[10,08,08,08,08,08,10,10,08,08,08,08,08,08,08],
		[10,08,08,10,10,10,10,10,10,08,08,08,08,08,08]
	],
	mapChip:{
		0:{ground:{divide:true,lt:{image:"kusa1-tuti1",x:0,y:4},rt:{image:"kusa1-tuti1",x:1,y:4},lb:{image:"kusa1-tuti1",x:0,y:9},rb:{image:"kusa1-tuti1",x:1,y:9}},
		object:{image:"",x:0,y:0},accessories:{image:"",x:0,y:0},canOn:true},
		1:{ground:{divide:true,lt:{image:"kusa1-tuti1",x:0,y:4},rt:{image:"kusa1-tuti1",x:1,y:0},lb:{image:"kusa1-tuti1",x:0,y:9},rb:{image:"kusa1-tuti1",x:1,y:3}},
		object:{image:"",x:0,y:0},accessories:{image:"",x:0,y:0},canOn:true},
		2:{ground:{divide:true,lt:{image:"kusa1-tuti1",x:0,y:8},rt:{image:"kusa1-tuti1",x:1,y:2},lb:{image:"kusa1-tuti1",x:0,y:9},rb:{image:"kusa1-tuti1",x:1,y:3}},
		object:{image:"",x:0,y:0},accessories:{image:"",x:0,y:0},canOn:true},
		3:{ground:{divide:true,lt:{image:"kusa1-tuti1",x:0,y:8},rt:{image:"kusa1-tuti1",x:1,y:2},lb:{image:"kusa1-tuti1",x:0,y:5},rb:{image:"kusa1-tuti1",x:1,y:1}},
		object:{image:"",x:0,y:0},accessories:{image:"",x:0,y:0},canOn:true},
		4:{ground:{divide:true,lt:{image:"kusa1-tuti1",x:0,y:8},rt:{image:"kusa1-tuti1",x:1,y:8},lb:{image:"kusa1-tuti1",x:0,y:5},rb:{image:"kusa1-tuti1",x:1,y:5}},
		object:{image:"",x:0,y:0},accessories:{image:"",x:0,y:0},canOn:true},
		5:{ground:{divide:true,lt:{image:"kusa1-tuti1",x:0,y:2},rt:{image:"kusa1-tuti1",x:1,y:8},lb:{image:"kusa1-tuti1",x:0,y:1},rb:{image:"kusa1-tuti1",x:1,y:5}},
		object:{image:"",x:0,y:0},accessories:{image:"",x:0,y:0},canOn:true},
		6:{ground:{divide:true,lt:{image:"kusa1-tuti1",x:0,y:2},rt:{image:"kusa1-tuti1",x:1,y:8},lb:{image:"kusa1-tuti1",x:0,y:3},rb:{image:"kusa1-tuti1",x:1,y:9}},
		object:{image:"",x:0,y:0},accessories:{image:"",x:0,y:0},canOn:true},
		7:{ground:{divide:true,lt:{image:"kusa1-tuti1",x:0,y:0},rt:{image:"kusa1-tuti1",x:1,y:4},lb:{image:"kusa1-tuti1",x:0,y:3},rb:{image:"kusa1-tuti1",x:1,y:9}},
		object:{image:"",x:0,y:0},accessories:{image:"",x:0,y:0},canOn:true},
		8:{ground:{image:"kusa1",x:0,y:4},object:{image:"",x:0,y:0},accessories:{image:"",x:0,y:0},canOn:true},
		9:{ground:{image:"kusa1-tuti1",x:0,y:4},object:{image:"",x:0,y:0},accessories:{image:"",x:0,y:0},canOn:true},
		10:{ground:{image:"koori1",x:0,y:4},object:{image:"",x:0,y:0},accessories:{image:"",x:0,y:0},canOn:false}
	},
	creatures:[{
		id:"man",
		creature:"npc",
		position:{x:1,y:1},
		image:"pipo-charachip001",
		size:2,
		speak:[
			{event:"turnToHero"},
			{event:"speak",sentence:"zキーで会話終了です"}
		]
	},
	{
		id:"dog",
		creature:"npc",
		position:{x:4,y:4},
		direction:"left",
		image:"pipo-charachip009b",
		size:2,
		speak:[
			{event:"turnToHero"},
			{event:"speak",sentence:"氷のマスは通れないわん!"},
			{event:"speak",sentence:"実際に歩いて確かめるといいわん!"},
			{event:"turn",direction:"left"}
		]
	},
	{
		id:"woman",
		creature:"npc",
		position:{x:3,y:1},
		image:"pipo-charachip002",
		size:2,
		speak:[
			{event:"turnToHero"},
			{event:"speak",sentence:"右向け右!"},
			{event:"turn",direction:"right",target:"hero"},
			{event:"speak",sentence:"左向け左!"},
			{event:"turn",direction:"left",target:"hero"},
			{event:"turn",direction:"down"}
		]
	},
	{
		id:"5",
		creature:"npc",
		position:{x:5,y:1},
		image:"pipo-charachip003",
		size:2,
		speak:[
			{event:"turnToHero"},
			{event:"speak",sentence:"強制移動イベントだよ"},
			{event:"move",directions:["down","down"],target:"hero"},
			{event:"turnToHero"},
			{event:"speak",sentence:"上から話しかけると貫通するのは仕様だよ"}
		]
	},
	{
		id:"6",
		creature:"npc",
		position:{x:1,y:3},
		image:"pipo-charachip004",
		size:2,
		speak:[
			{event:"turnToHero"},
			{event:"branch",flag:"test",false:[
				{event:"speak",sentence:"バトル開始"},
				{event:"battle",data:{enemy:[0,'T',1,'F']},win:[
					{event:"speak",sentence:"私の負けだ"},
					{event:"setFlag",flag:"test",value:"true"}
				],lose:[
					{event:"speak",sentence:"私の勝ちだ　また挑戦してくれ"}
				]},
			],
		true:[
			{event:"speak",sentence:"私の負けだ"}
		]}
		]
	},
	{
		id:"group1",
		creature:"npc",
		position:{x:8,y:0},
		image:"pipo-charachip018",
		size:2,
		speak:[
			{event:"turnToHero"},
			{event:"branch",flag:"group1",false:[
				{event:"speak",sentence:"さあ勝負だ"},
				{event:"battle",data:{enemy:[0,'T',1,'T',2,'F']},win:[
					{event:"speak",sentence:"素晴らしい!他のメンバーにも挑戦してくれ。"},
					{event:"setFlag",flag:"group1",value:"true"}
				],lose:[
					{event:"speak",sentence:"何度でも挑戦を受けてやるからまた来てくれ。"}
				]},
			],
		true:[
			{event:"speak",sentence:"私の試練はすでにクリアしているぞ。"}
		]},
		{event:"turn",direction:"down"}
		]
	},
	{
		id:"group2",
		creature:"npc",
		position:{x:10,y:0},
		image:"pipo-charachip018f",
		size:2,
		speak:[
			{event:"turnToHero"},
			{event:"branch",flag:"group2",false:[
				{event:"speak",sentence:"さあ勝負だ"},
				{event:"battle",data:{enemy:[9,'T',12,'T',11,'F',6,'F']},win:[
					{event:"speak",sentence:"素晴らしい!他のメンバーにも挑戦してくれ。"},
					{event:"setFlag",flag:"group2",value:"true"}
				],lose:[
					{event:"speak",sentence:"何度でも挑戦を受けてやるからまた来てくれ。"}
				]},
			],
		true:[
			{event:"speak",sentence:"私の試練はすでにクリアしているぞ。"}
		]},
		{event:"turn",direction:"down"}
		]
	},
	{
		id:"group3",
		creature:"npc",
		position:{x:12,y:0},
		image:"pipo-charachip018g",
		size:2,
		speak:[
			{event:"turnToHero"},
			{event:"branch",flag:"group3",false:[
				{event:"speak",sentence:"さあ勝負だ"},
				{event:"battle",data:{enemy:[13,'T',15,'T',17,'F',18,'F']},win:[
					{event:"speak",sentence:"素晴らしい!他のメンバーにも挑戦してくれ。"},
					{event:"setFlag",flag:"group3",value:"true"}
				],lose:[
					{event:"speak",sentence:"何度でも挑戦を受けてやるからまた来てくれ。"}
				]},
			],
		true:[
			{event:"speak",sentence:"私の試練はすでにクリアしているぞ。"}
		]},
		{event:"turn",direction:"down"}
		]
	},
	{
		id:"groupLeader",
		creature:"npc",
		position:{x:14,y:1},
		image:"pipo-charachip016b",
		size:2,
		speak:[
			{event:"turnToHero"},
			{event:"branch",flag:"group1",false:[{event:"speak",sentence:"上にいる三人全員に勝利したら私に話かけてくれ。"},{event:"turn",direction:"down"},{event:"end"}],true:[]},
			{event:"branch",flag:"group2",false:[{event:"speak",sentence:"上にいる三人全員に勝利したら私に話かけてくれ。"},{event:"turn",direction:"down"},{event:"end"}],true:[]},
			{event:"branch",flag:"group3",false:[{event:"speak",sentence:"上にいる三人全員に勝利したら私に話かけてくれ。"},{event:"turn",direction:"down"},{event:"end"}],true:[]},
			{event:"speak",sentence:"ブラボー!!"},
			{event:"turn",direction:"down"}
		]
	},
	{
		creature:"chest",
		item:["薬","武器","防具"],
		position:{x:0,y:4},
		image:{
			close:{image:"base",x:6,y:20},
			open:{image:"base",x:6,y:21}
		}
	}
]
}
var mMyChara;
SaveDatabase.loadSaveData(()=>{
	PreImage.preLoadMapChip(mMapData,()=>{
		Map.setMap(mMapData)
		mMyChara=Map.createHero(3,3,"5_field/1345010501");
		KeyMonitor.setMapPage();
	})
	window.addEventListener('message', function(event,aMessage) {
		Frame.closeFrame();
	}, false);
});
function getDatabase(){
	return SaveDatabase;
}
