class Mas{
	constructor(aMas){
		this.chara=null;//このマスにいるキャラ
		//マス
		this.tag=document.createElement("div");
		this.tag.style.display="inline-block";
		this.tag.style.width=mMasSize+"px";
		this.tag.style.height=mMasSize+"px";
		this.tag.style.overflow="hidden";
		//地面
		if(aMas.ground.divide==true){
			//さらに4分割
			this.groundLt=document.createElement("div");
			this.groundLt.style.overflow="hidden";
			this.groundLt.style.display="inline-block";
			this.groundLt.style.width=mMasSize/2+"px";
			this.groundLt.style.height=mMasSize/2+"px";
			this.groundLt.style.marginTop="0";
			this.groundLt.style.marginLeft="0";
			this.groundLtImg=document.createElement("img");
			this.groundLtImg=PreImage.getImage(aMas.ground.lt.image);
			this.groundLtImg.style.marginTop=-(mMasSize/2)*aMas.ground.lt.y+"px";
			this.groundLtImg.style.marginLeft=-(mMasSize/2)*aMas.ground.lt.x+"px";
			this.groundLt.appendChild(this.groundLtImg);
			this.groundRt=document.createElement("div");
			this.groundRt.style.overflow="hidden";
			this.groundRt.style.display="inline-block";
			this.groundRt.style.width=mMasSize/2+"px";
			this.groundRt.style.height=mMasSize/2+"px";
			this.groundRt.style.marginTop="0";
			this.groundRt.style.marginRight="0";
			this.groundRtImg=document.createElement("img");
			this.groundRtImg=PreImage.getImage(aMas.ground.rt.image);
			this.groundRtImg.style.marginTop=-(mMasSize/2)*aMas.ground.rt.y+"px";
			this.groundRtImg.style.marginLeft=-(mMasSize/2)*aMas.ground.rt.x+"px";
			this.groundRt.appendChild(this.groundRtImg);
			this.groundLb=document.createElement("div");
			this.groundLb.style.overflow="hidden";
			this.groundLb.style.display="inline-block";
			this.groundLb.style.width=mMasSize/2+"px";
			this.groundLb.style.height=mMasSize/2+"px";
			this.groundLb.style.marginBotton="0";
			this.groundLb.style.marginLeft="0";
			this.groundLbImg=document.createElement("img");
			this.groundLbImg=PreImage.getImage(aMas.ground.lb.image);
			this.groundLbImg.style.marginTop=-(mMasSize/2)*aMas.ground.lb.y+"px";
			this.groundLbImg.style.marginLeft=-(mMasSize/2)*aMas.ground.lb.x+"px";
			this.groundLb.appendChild(this.groundLbImg);
			this.groundRb=document.createElement("div");
			this.groundRb.style.overflow="hidden";
			this.groundRb.style.display="inline-block";
			this.groundRb.style.width=mMasSize/2+"px";
			this.groundRb.style.height=mMasSize/2+"px";
			this.groundRb.style.marginBottom="0";
			this.groundRb.style.marginRight="0";
			this.groundRbImg=document.createElement("img");
			this.groundRbImg=PreImage.getImage(aMas.ground.rb.image);
			this.groundRbImg.style.marginTop=-(mMasSize/2)*aMas.ground.rb.y+"px";
			this.groundRbImg.style.marginLeft=-(mMasSize/2)*aMas.ground.rb.x+"px";
			this.groundRb.appendChild(this.groundRbImg);
		}
		else{
			this.ground=document.createElement("img");
			this.ground=PreImage.getImage(aMas.ground.image)
			this.ground.style.marginTop=-mMasSize*aMas.ground.y+"px";
			this.ground.style.marginLeft=-mMasSize*aMas.ground.x+"px";
		}
		//オブジェクト
		this.object=document.createElement("img");
		this.object.img=getImagePath(aMas.object.image);
		this.object.style.width=this.object.width*mMasSize/mMasChipSize+"px";
		this.object.style.height=this.object.height*mMasSize/mMasChipSize+"px";
		this.object.style.marginTop=-mMasSize*aMas.object.y+"px";
		this.object.style.marginLeft=-mMasSize*aMas.object.x+"px";
		//装飾品
		this.accessories=document.createElement("img");
		this.accessories.img=getImagePath(aMas.accessories.image);
		this.accessories.style.width=this.accessories.width*mMasSize/mMasChipSize+"px";
		this.accessories.style.height=this.accessories.height*mMasSize/mMasChipSize+"px";
		this.accessories.style.marginTop=-mMasSize*aMas.accessories.y+"px";
		this.accessories.style.marginLeft=mMasSize*aMas.accessories.x;

		this.canOnFlag=aMas.canOn;//このマスを通過できるか
		if(aMas.ground.divide==true){
			this.tag.appendChild(this.groundLt);
			this.tag.appendChild(this.groundRt);
			this.tag.appendChild(document.createElement("br"))
			this.tag.appendChild(this.groundLb);
			this.tag.appendChild(this.groundRb);
		}
		else{
			this.tag.appendChild(this.ground);
		}
		this.tag.appendChild(this.object);
		this.tag.appendChild(this.accessories);
	}
	getElement(){
		return this.tag;
	}
	//このマスが通過可能か
	canOn(){
		return this.canOnFlag;
	}
	//このマスにキャラが乗った
	onChara(aCreature){
		this.chara=aCreature;
	}
	//このマスからキャラが移動した
	outChara(){
		this.chara=null;
	}
	//このマスにいるキャラを返す
	getOnChara(){
		return this.chara;
	}
}
var mMasSize=64;
var mMasChipSize=16;
function getImagePath(aPath){
	if(aPath=="") return "";
	return "../image/map/mapchip2/MapChip/"+aPath+".png";
}
